//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammerAL.Analyzers.ControllerRequiredAuthAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgrammerAL.Analyzers.ControllerRequiredAuthAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both controller and endpoint have auth attribute, choose one..
        /// </summary>
        internal static string ControllerAndEndpointHaveAuthAttributeDescription {
            get {
                return ResourceManager.GetString("ControllerAndEndpointHaveAuthAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both controller &apos;{0}&apos; and endpoint &apos;{1}&apos; have auth attribute, choose one.
        /// </summary>
        internal static string ControllerAndEndpointHaveAuthAttributeMessageFormat {
            get {
                return ResourceManager.GetString("ControllerAndEndpointHaveAuthAttributeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both controller and endpoint have auth attribute.
        /// </summary>
        internal static string ControllerAndEndpointHaveAuthAttributeTitle {
            get {
                return ResourceManager.GetString("ControllerAndEndpointHaveAuthAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint does not have an auth attribute. it is required because the parent controller also does not have one..
        /// </summary>
        internal static string EndpointMissingAuthAttributeDescription {
            get {
                return ResourceManager.GetString("EndpointMissingAuthAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The endpoint &apos;{0}&apos; does not have an auth attribute. It is required because the parent controller &apos;{1}&apos; also does not have one..
        /// </summary>
        internal static string EndpointMissingAuthAttributeMessageFormat {
            get {
                return ResourceManager.GetString("EndpointMissingAuthAttributeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint does not have an auth attribute.
        /// </summary>
        internal static string EndpointMissingAuthAttributeTitle {
            get {
                return ResourceManager.GetString("EndpointMissingAuthAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller requires authentication attribute on itself or all endpoints..
        /// </summary>
        internal static string MissingAnyAuthAttributeDescription {
            get {
                return ResourceManager.GetString("MissingAnyAuthAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller &apos;{0}&apos; requires an auth attribute or an attribute on all of its endpoints.
        /// </summary>
        internal static string MissingAnyAuthAttributeMessageFormat {
            get {
                return ResourceManager.GetString("MissingAnyAuthAttributeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller does not have any auth attributes on the controller or endpoints.
        /// </summary>
        internal static string MissingAnyAuthAttributeTitle {
            get {
                return ResourceManager.GetString("MissingAnyAuthAttributeTitle", resourceCulture);
            }
        }
    }
}
